#!/usr/bin/env python

import os
import tempfile
from subprocess import check_call
from path import path

ES_DOWNLOAD_URL = ('http://download.elasticsearch.org/elasticsearch/'
                   'elasticsearch/elasticsearch-0.20.4.tar.gz')
ES_KIT_DIRNAME = 'elasticsearch-0.20.4'

ES_PREFIX = os.environ.get('ES_PREFIX')


def main():
    if not ES_PREFIX:
        print '$ES_PREFIX not set'
        return

    prefix = path(ES_PREFIX)
    if prefix.isdir():
        print '%s already exists' % prefix
        return

    tmp = path(tempfile.gettempdir())
    try:
        check_call("curl -L '%s' | tar xzf -" % (ES_DOWNLOAD_URL,),
                   shell=True, cwd=tmp)
        path(tmp / ES_KIT_DIRNAME).rename(ES_PREFIX)
        print "Installed to %s" % (ES_PREFIX,)

    finally:
        tmp.rmtree()


if __name__ == '__main__':
    main()
